/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AuthSession } from "./AuthSession";
import { AuthSessionCountArgs } from "./AuthSessionCountArgs";
import { AuthSessionFindManyArgs } from "./AuthSessionFindManyArgs";
import { AuthSessionFindUniqueArgs } from "./AuthSessionFindUniqueArgs";
import { CreateAuthSessionArgs } from "./CreateAuthSessionArgs";
import { UpdateAuthSessionArgs } from "./UpdateAuthSessionArgs";
import { DeleteAuthSessionArgs } from "./DeleteAuthSessionArgs";
import { AuthSessionService } from "../authSession.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AuthSession)
export class AuthSessionResolverBase {
  constructor(
    protected readonly service: AuthSessionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AuthSession",
    action: "read",
    possession: "any",
  })
  async _authSessionsMeta(
    @graphql.Args() args: AuthSessionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AuthSession])
  @nestAccessControl.UseRoles({
    resource: "AuthSession",
    action: "read",
    possession: "any",
  })
  async authSessions(
    @graphql.Args() args: AuthSessionFindManyArgs
  ): Promise<AuthSession[]> {
    return this.service.authSessions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AuthSession, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AuthSession",
    action: "read",
    possession: "own",
  })
  async authSession(
    @graphql.Args() args: AuthSessionFindUniqueArgs
  ): Promise<AuthSession | null> {
    const result = await this.service.authSession(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AuthSession)
  @nestAccessControl.UseRoles({
    resource: "AuthSession",
    action: "create",
    possession: "any",
  })
  async createAuthSession(
    @graphql.Args() args: CreateAuthSessionArgs
  ): Promise<AuthSession> {
    return await this.service.createAuthSession({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AuthSession)
  @nestAccessControl.UseRoles({
    resource: "AuthSession",
    action: "update",
    possession: "any",
  })
  async updateAuthSession(
    @graphql.Args() args: UpdateAuthSessionArgs
  ): Promise<AuthSession | null> {
    try {
      return await this.service.updateAuthSession({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AuthSession)
  @nestAccessControl.UseRoles({
    resource: "AuthSession",
    action: "delete",
    possession: "any",
  })
  async deleteAuthSession(
    @graphql.Args() args: DeleteAuthSessionArgs
  ): Promise<AuthSession | null> {
    try {
      return await this.service.deleteAuthSession(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
